version: '3'
services:
  sk03-web:
    container_name: sk03-web
    build:
      context: ./backend  # Kontext složky backend
      dockerfile: Dockerfile  # Název Dockerfile (velké "D")
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - DB_User=${DB_User}
      - DB_Password=${DB_Password}
      - DB_Host=sk03-mongo
      - DB_Port=50002
    volumes:
      - "/home/cerny/logs/sk03:/app/logs"  # Pro logy
    networks:
      - cdb-network
      - internalnetwork
    depends_on:
      - mongo-db

  sk03-frontend:
    container_name: sk03-frontend
    build:
      context: ./frontend   # Kontext složky, kde se nachází Dockerfile pro frontend
      dockerfile: Dockerfile  # Dockerfile pro React aplikaci ve složce frontend
    ports:
      - "3002:80"  # Naslouchá na portu 3002, přesměruje na port 80 v kontejneru (Nginx)

  mongo-db:
    container_name: sk03-mongo
    image: mongo:latest  # Použijeme oficiální MongoDB image
    restart: always
    command: ["mongod", "--port", "50002", "--quiet", "--logpath", "/dev/null"]  # Setting internal MongoDB port
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_User}  # Root uživatel
      MONGO_INITDB_ROOT_PASSWORD: ${DB_Password}  # Root heslo
      MONGO_INITDB_DATABASE: bookCatalog
    ports:
      - "50002:50002"  # Port MongoDB (default)
    networks:
      - internalnetwork
  
  mongo-express:
    container_name: sk03-mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - "10002:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${DB_User}:${DB_Password}@sk03-mongo:50002/bookCatalog?authSource=admin"
    depends_on:
      - mongo-db
    networks:
      - internalnetwork

networks:
  cdb-network:
    name: cdb-network
    driver: bridge
    external: true
  internalnetwork:
    name: internalnetwork
    driver: bridge
    external: false
